### PR TITLE
Extend ServiceDiscoveryConfig for other platforms

### PR DESCRIPTION
**Pull request by 0xgirish**
- [x] EC2
- [x] GCE
- [x] Azure
- [x] Digitalocean
- [x] Consul
- [x] Dockerswarm
- [x] DNS

### CODE REVIEW

**Comment by 0xgirish** [comment]
@AlekSi, please review

**Comment by AlekSi** [comment]
May you add a test please? See https://github.com/percona/promconfig/tree/main/testdata

**Review by AlekSi — CHANGES_REQUESTED** [review]
May you please add non-null example configurations to both JSON and YAML file to check that this actually works?

**Comment by 0xgirish** [comment]
I will add the tests by EOD

**Comment by kmrgirish** [comment]
@AlekSi any update on this

**Review by artemgavrilov — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Review by palash25 — APPROVED** [review]

**Comment by artemgavrilov** [comment]
@zkmrgirish thanks)

**Pull request merged**
